name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Setup
        run: npm i -g @antfu/ni
      - name: Install
        run: nci
      - name: Build
        run: nr build

      - name: Preparing a release 🚀
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 21
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_GLOBAL_TOKEN }}
